# Site settings
title: Репозиторий дополнений KODI
description: Репозиторий дополнений KODI от разработчика vl.maksime
author: Владимир Максименко
email: vl.maksime@gmail.com
github_username: vlmaksime

baseurl: "/repository.vlmaksime"
url: "https://vlmaksime.github.io"

google_analytics: UA-131785381-1
paginate: 20
per_page: 20
paginate_path: "/page:num/"

# Collections
collections:
  addons:
    output: true
    permalink: /releases/:path/

# Build settings
markdown: kramdown
plugins: [jekyll-paginate, jekyll-gist]
exclude: [sources\]
remote_theme: "vlmaksime/material-jekyll-theme"
