# Site settings
title: Репозиторий дополнений KODI
description: Репозиторий дополнений KODI от разработчика vl.maksime
author: Владимир Максименко
email: vl.maksime@gmail.com
github_username: vlmaksime

baseurl: "/repository.vlmaksime"
url: "https://vlmaksime.github.io"

google_analytics: UA-131785381-1

# Collections
collections:
  addons:
    output: true
    permalink: /releases/:path/

# Build settings
markdown: kramdown
exclude: [sources\]
remote_theme: "vlmaksime/material-jekyll-theme"
